<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>
    <section class="title_section">
        <h1 class="home_title">The best way to learn Japaneese</h1>
        <p>Welcome to Kuizuquiz, learn Japanese in the most effective and fun way.</p>
        <p>Start now and level up your knowledge.</p>
    </section>


    

</body>
</html>