<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/home.css">

</head>
<body>
    <header>
        <img src="images/logo.png" alt="logo" class="logo" width="50px">
        <nav class="navbar">
            <ul>
                <li><a href="">Home</a></li>
                <li><a href="">Materials</a></li>
                <li><a href="">Kanji quiz</a></li>
                <li><a href="">Account</a></li>
            </ul>
        </nav>
    </header>
    <main>
    <?php $this->controller->renderView();?>







    </main>
        
</body>
</html>